kind: pipeline
name: default

platform:
  arch: amd64

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags

  - name: lint
    image: golang
    volumes:
      - name: deps
        path: /go
    commands:
      - "curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin "
      - golangci-lint run
    when:
      event:
        exclude:
          - tag

  - name: release
    image: golang
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: deps
        path: /go
    commands:
      - curl -sL https://git.io/goreleaser | bash
    when:
      event: tag

volumes:
  - name: deps
    temp: {}